language: node_js

node_js:
  - "node"

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/1408f3d940518dc722ef'
    on_success: always
    on_failure: always
    on_start: never

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - npm install etch@"<1.0.0"

script:
  - npm test
